server:
  port: 1217
logging:
  level:
    org.springframework: ERROR
    com.travel: DEBUG
    org.keycloak: DEBUG
spring:
  devtools:
    restart:
      enabled: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
            implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: false
  datasource:
    url: jdbc:mysql://192.178.10.133:3306/e_services_be_user?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: Care@3210
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
      host: smtp.dreamhost.com
      username: altxbesupport@travtronics.com
      password: Babji@310
      port: 587
      properties:
        mail:
          smtp:
            starttls:
              enable: true
              required: true
            auth: true 
keycloak:
  auth-server-url: http://192.178.10.133:8080/auth
  realm: Eservices
  resource: eservice-app
  public-client: true
  security-constraints:
  - auth-roles:
    - AdminRole
    security-collections:
    - patterns:
      - /login-management
  ssl-required: none
  use-resource-role-mappings: true
  
com :
   travel :
      keycloak :
         urlKeycloakHost : http://192.178.10.133:8080/
         client_secret : 0a739918-4210-41bd-bef9-fdcf0a7f6eb5
         user : admin
         credentials : password
         client_id : eservice-app
         default-password : travel@deafult!12345Password
         
      encryption :
         keyValue: aesEncryptionKey
         algorithm: AES/CBC/PKCS5PADDING
         keySize: 16
         publicKey: TravelEncryptKey
      roles :
        adminRoleId : 2ff11bf8-e739-4531-a3bc-926d1b221213
        feUserRoleId : 02c43376-1be2-4142-afeb-181ac2257ba7
        beUserRoleId : cf5ce4a1-45a8-4539-bff0-e67f4832f4e7
        
      tech:
         optionaudit:
           email:
            fromMailId: support@eserv.com
            mailIdName: EservExecutive
            resetPassword: https://eserv.dev.com/pages/reset-kc-password?i
           url:
             redirect_uri_dashboard: http://localhost:4300/register
             defaultPassword: Tr@vtronicsDefaultPassword@!21#993453486543Test!
             google_auth_host: https://accounts.google.com/o/oauth2/
             google_secret_id: fWlnpD782AMb7oNcPOPkJ-Mj
             google_client_id: 1095081353757-d42hoa54gnkmgku54mvf8kt0r942ftc8.apps.googleusercontent.com
             google_userprofile: https://openidconnect.googleapis.com/v1/userinfo
             quoteSendUrl: http://localhost:8080/cYSokaY?i=
           

